### ISSUE TITLE
Add "[...]" when trucating posts

### ISSUE THREAD

**Issue by cinnamon-bun** [rogeriochaves/feedless#2]
Awesome project!

Feedless chops down long posts from the rest of SSB without letting people know this is happening.  This could result in some bad text, like this silly example

`I really like being badminton coach`
--> `I really like being bad`

I'm sure we could invent much worse examples which would result in people getting mad at you online.

It would help to add `[...]` whenever chopping a post, though this doesn't completely solve the problem --> `I really like being bad[...]`

**Comment by rogeriochaves** [comment]
yeah, actually I don't truncate post, I split them, so if you have a post with 200 characters, feedless will show one with 140 and another one with 60, I want to improve that to at least cut whole words and not a word in the middle, because that is what people would usually do on twitter

but you are right that even so it might be better to add some indication like people do on twitter with 1/ or even the [...]

**Comment by rogeriochaves** [comment]
done, I've added the 1/ thingie, personally its easier for me to follow now, what do you think?

<img width="597" alt="image" src="https://user-images.githubusercontent.com/792201/81498078-1eb9ea00-92c3-11ea-849c-17332a0639b9.png">

**Comment by cinnamon-bun** [comment]
Nice, that helps it make sense!
