### ISSUE TITLE
Is Feedless introducing a new sub-protocol ?

### ISSUE THREAD

**Issue by zicmama** [rogeriochaves/feedless#8]
I like the short message style Feedless is adopting!!
But it is not really convenient to display "post" type message as it spread a lot of lines...

Maybe you should consider introducing a new SSB message type specifiic to FeedLess constraint?

For example, my personnal experience with SSB App, I introduced cesium_geoPoint data added to my Feed, only my client understand and use.
```
sbotc publish '{"type":"cesium_geoPoint.lat","text":"'"$geopointlat"'"}' 
sbotc publish '{"type":"cesium_geoPoint.lon","text":"'"$geopointlon"'"}' 

sbotc publish '{"type":"ipfsnodeid","text":"'"$(ipfs id | jq -r .ID)"'"}' 
sbotc publish '{"type":"ipfstryme","text":"'"$(ipfs id | jq -r .Addresses[] | tail -n 1)"'"}' 
```

**Comment by zicmama** [comment]
Or maybe you are right. It is best keeping "post" message type !!

As conversation is based on a "secret" thread (p2p established).
The display problem happens for regular "public" messages display

**Comment by rogeriochaves** [comment]
Thank you, glad you liked! I prefer reading short messages myself :D

Yeah the reason I'm using "post" is because I didn't want to loose all the amazing content that is already on ssb network, instead I prefer to just convert and split big posts into many short ones, so we have a good interop, also because feedless short messages look good too on patchwork

**Comment by rogeriochaves** [comment]
So far interop with posts from other SSB clients are working very well, so I'm keeping the "post" type
